name: Scrape Contributions

on:
  schedule:
    - cron: '30 */2 * * *'  # Runs every 2 hours at 30 minutes past the hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary packages
        run: |
          sudo apt purge -y chromium-browser
          sudo apt install -y chromium-browser
          pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Run the scraping script
        run: python scraper.py

      - name: Commit changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add commits.txt
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0  # Avoid failing if no changes
          git push
