name: Scrape Total Commits

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests

      - name: Run the scrape script
        run: |
          python get_commits.py
          cat total_commits.txt

      - name: Update commits.md with total commits
        run: |
          echo "Total Commits: $(cat total_commits.txt)" > commits.md
          git config --local user.email "jperlmutter1@gmail.com"
          git config --local user.name "jear-bear"
          git add commits.md
          git commit -m "Update commits.md with total commits"
          git push
