name: Scrape GitHub Commits

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (you can adjust this)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install selenium beautifulsoup4 webdriver-manager

    - name: Run get_commits.py
      run: python get_commits.py

    - name: Display total commits
      run: cat total_commits.txt

    - name: Push changes to commits.md
      run: |
        git config --global user.email "jperlmutter1@example.com"
        git config --global user.name "jaredperlmutter"
        git add total_commits.txt  # or commits.md if you are updating that
        git commit -m "Update total commits count" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Jear-Bear/Jear-Bear.git main --quiet --force
